version: '3.9'

services:
  gateway:
    build:
      context: ../breaditnow-gateway
    image: breaditnow-gateway:latest
    container_name: breaditnow-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_TOKEN_SECRET_KEY: ${AUTH_TOKEN_SECRET_KEY}
    networks:
      - bin-network

  auth-api:
    build:
      context: ../breaditnow-auth-api
    image: breaditnow-auth-api:latest
    container_name: breaditnow-auth-api
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      OAUTH2_KAKAO_CLIENT_ID: ${OAUTH2_KAKAO_CLIENT_ID}
      OAUTH2_KAKAO_CLIENT_SECRET: ${OAUTH2_KAKAO_CLIENT_SECRET}
      OAUTH2_KAKAO_REDIRECT_URI: ${OAUTH2_KAKAO_REDIRECT_URI}
      OAUTH2_NAVER_CLIENT_ID: ${OAUTH2_NAVER_CLIENT_ID}
      OAUTH2_NAVER_CLIENT_SECRET: ${OAUTH2_NAVER_CLIENT_SECRET}
      OAUTH2_NAVER_REDIRECT_URI: ${OAUTH2_NAVER_REDIRECT_URI}
      AUTH_TOKEN_SECRET_KEY: ${AUTH_TOKEN_SECRET_KEY}
      REFRESH_COOKIE_KEY: ${REFRESH_COOKIE_KEY}
    volumes:
      - ${LOG_VOLUME_PATH}/auth-api:/app/logs/auth-api
    networks:
      - bin-network

  customer-api:
    build:
      context: ../breaditnow-customer-api
    image: breaditnow-customer-api:latest
    container_name: breaditnow-customer-api
    ports:
      - "9001:9001"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      OAUTH2_KAKAO_CLIENT_ID: ${OAUTH2_KAKAO_CLIENT_ID}
      AWS_S3_CREDENTIALS_ACCESS_KEY: ${AWS_S3_CREDENTIALS_ACCESS_KEY}
      AWS_S3_CREDENTIALS_SECRET_KEY: ${AWS_S3_CREDENTIALS_SECRET_KEY}
      FCM_PROJECT_ID: ${FCM_PROJECT_ID}
    volumes:
      - ${LOG_VOLUME_PATH}/customer-api:/app/logs/customer-api
    networks:
      - bin-network

  owner-api:
    build:
      context: ../breaditnow-owner-api
    image: breaditnow-owner-api:latest
    container_name: breaditnow-owner-api
    ports:
      - "9002:9002"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      OAUTH2_KAKAO_CLIENT_ID: ${OAUTH2_KAKAO_CLIENT_ID}
      AUTH_TOKEN_SECRET_KEY: ${AUTH_TOKEN_SECRET_KEY}
      AWS_S3_CREDENTIALS_ACCESS_KEY: ${AWS_S3_CREDENTIALS_ACCESS_KEY}
      AWS_S3_CREDENTIALS_SECRET_KEY: ${AWS_S3_CREDENTIALS_SECRET_KEY}
      FCM_PROJECT_ID: ${FCM_PROJECT_ID}
    volumes:
      - ${LOG_VOLUME_PATH}/owner-api:/app/logs/owner-api
    networks:
      - bin-network

networks:
  bin-network:
    external: true
