version: '3.9'

services:
  gateway:
    image: ${DOCKER_USERNAME}/breaditnow-gateway:latest
    container_name: breaditnow-gateway
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/gateway:/app/logs/gateway
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M

  auth-api:
    image: ${DOCKER_USERNAME}/breaditnow-auth-api:latest
    container_name: breaditnow-auth-api
    ports:
      - "9000:9000"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/auth-api:/app/logs/auth-api
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M

  customer-api:
    image: ${DOCKER_USERNAME}/breaditnow-customer-api:latest
    container_name: breaditnow-customer-api
    ports:
      - "9001:9001"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/customer-api:/app/logs/customer-api
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M

  owner-api:
    image: ${DOCKER_USERNAME}/breaditnow-owner-api:latest
    container_name: breaditnow-owner-api
    ports:
      - "9002:9002"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/owner-api:/app/logs/owner-api
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M

  reservation-api:
    image: ${DOCKER_USERNAME}/breaditnow-reservation-api:latest
    container_name: breaditnow-reservation-api
    ports:
      - "9003:9003"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/reservation-api:/app/logs/reservation-api
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M

  notification-api:
    image: ${DOCKER_USERNAME}/breaditnow-notification-api:latest
    container_name: breaditnow-notification-api
    ports:
      - "9004:9004"
    restart: always
    env_file:
      - .env
    volumes:
      - ${LOG_VOLUME_PATH}/notification-api:/app/logs/notification-api
    networks:
      - bin-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M

networks:
  bin-network:
    external: true