spring:
  config:
    activate:
      on-profile: local

  docker:
    compose:
      enabled: true
      file: ./docker/docker-compose.yml

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
