server:
  port: 8080

spring:
  application:
    name: gateway

  banner:
    location: static/banner/banner.txt
    charset: UTF-8

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  webflux:
    static-path-pattern: "/static/**"

  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
          args:
            preLogger: true
            postLogger: true

auth:
  token:
    secret-key: ${AUTH_TOKEN_SECRET_KEY}

logging:
  config: classpath:logging/logback-spring.xml
  file:
    path: logs
  level:
    root: INFO
    com.breaditnow.gateway.filter: DEBUG

webhook:
  discord:
    username: ${DISCORD_USERNAME}
    avatar-url: ${DISCORD_AVATAR_URL}
    error-url: ${DISCORD_ERROR_URL}
