spring:
  config:
    activate:
      on-profile: local

  cloud:
    gateway:
      routes:
        - id: oauth2
          uri: http://localhost:9000/
          predicates:
            - Path=/oauth2/authorization/**, /oauth/callback/**

        - id: auth-api
          uri: http://localhost:9000/
          predicates:
            - Path=/auth-api/**
          filters:
            - RewritePath=/auth-api/(?<segment>.*), /$\{segment}

        - id: customer-api
          uri: http://localhost:9001/
          predicates:
            - Path=/customer-api/**
          filters:
            - JwtAuthentication=ROLE_CUSTOMER
            - RewritePath=/customer-api/(?<segment>.*), /$\{segment}

        - id: owner-api
          uri: http://localhost:9002/
          predicates:
            - Path=/owner-api/**
          filters:
            - JwtAuthentication=ROLE_OWNER
            - RewritePath=/owner-api/(?<segment>.*), /$\{segment}

        - id: reservation-api
          uri: http://localhost:9003
          predicates:
            - Path=/reservation-api/**
          filters:
            - RewritePath=/reservation-api/(?<segment>.*), /$\{segment}

        - id: notification-api
          uri: http://localhost:9004
          predicates:
            - Path=/notification-api/**
          filters:
            - RewritePath=/notification-api/(?<segment>.*), /$\{segment}