server:
  port: 8080

spring:
  application:
    name: gateway

  banner:
    location: static/banner/banner.txt
    charset: UTF-8

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  webflux:
    static-path-pattern: "/static/**"

  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: oauth2
          uri: http://localhost:9000/
          predicates:
            - Path=/oauth2/authorization/**, /oauth/callback/**  # 소셜 로그인 처리

        - id: auth-api
          uri: http://localhost:9000/
          predicates:
            - Path=/auth-api/**
          filters:
            - RewritePath=/auth-api/(?<segment>.*), /$\{segment}

        - id: customer-api
          uri: http://localhost:9001/
          predicates:
            - Path=/customer-api/**
          filters:
            - JwtAuthentication=ROLE_CUSTOMER
            - RewritePath=/customer-api/(?<segment>.*), /$\{segment}

        - id: owner-api
          uri: http://localhost:9002/
          predicates:
            - Path=/owner-api/**
          filters:
            - JwtAuthentication=ROLE_OWNER
            - RewritePath=/owner-api/(?<segment>.*), /$\{segment}

auth:
  token:
    secret-key: ${AUTH_TOKEN_SECRET_KEY}

logging:
  config: classpath:logging/logback-spring.xml
  file:
    path: logs
  level:
    root: INFO
