spring:
  profiles:
    active: local
    group:
      local:
        - mysql-local
        - customer-local
        - owner-local

--- # local 설정
spring:
  config:
    activate:
      on-profile: local