spring:
  config:
    activate:
      on-profile: local

  docker:
    compose:
      enabled: true
      file: ./docker/docker-compose.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/breaditnow?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password:

  redis:
    host: localhost
    port: 6379
