spring:
  config:
    activate:
      on-profile: prod
    import: application-mysql-prod.yml

openapi:
  service:
    url: ${BREADITNOW_API_HTTPS_HOST}/owner-api

api:
  internal:
    customer-service:
      url: http://breaditnow-customer-api:9001