server:
  port: 9002

spring:
  application:
    name: owner-api

  banner:
    location: static/banner/banner.txt
    charset: UTF-8

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

geolocation:
  kakao:
    client-id: ${OAUTH2_KAKAO_CLIENT_ID}

logging:
  config: classpath:logging/logback-spring.xml
  file:
    path: logs
  level:
    root: INFO
