spring:
  config:
    activate:
      on-profile: local
    import: application-mysql-local.yml
  # RabbitMQ 연결 정보
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

aws:
  s3:
    bucket: bread-it-now-server
  credentials:
    access-key: ${AWS_S3_CREDENTIALS_ACCESS_KEY}
    secret-key: ${AWS_S3_CREDENTIALS_SECRET_KEY}
  region:
    static: ap-northeast-2
    auto: false
    stack:
      auto: false

# RabbitMQ queue, exchange, routing-key 정보
#rabbitmq:
#  favorite:
#    product:
#      exchangeName: favorite.product.exchange
#  queue.name: sample.queue
#  exchange.name: sample.exchange
