spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-mysql-prod.yml
      - application-redis-prod.yml

api:
  internal:
    customer-service:
      url: http://breaditnow-customer-api:9001
    owner-service:
      url: http://breaditnow-owner-api:9002
    reservation-service:
      url: http://breaditnow-reservation-api:9003